version: '3.8'

services:
  sv_taller1:
    container_name: $CAVStallerX1
    image: $CAVSbase
    environment:
      - DOMINIO=$CAVStaller.es
      - NAMEHOST=$CAVStaller1
    networks:
      my_network:
        ipv4_address: 172.80.10.1

  sv_taller2:
    container_name: $CAVStallerX2
    image: $CAVSbase
    environment:
      - DOMINIO=$CAVStaller.es
      - NAMEHOST=$cavstaller2
    networks:
      my_network:
        ipv4_address: 172.80.10.2 

  sv_taller3:
    container_name: $CAVSvtallerX3
    image: $CAVSbase
    environment:
      - DOMINIO=$CAVStaller.es
      - NAMEHOST=$CAVStaller3
    networks:
      my_network:
        ipv4_address: 172.80.10.3

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.10.0/24
